// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: cores/class_service.proto

package cores

import (
	context "context"
	pb "github.com/snple/kirara/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClassService_Create_FullMethodName          = "/cores.ClassService/Create"
	ClassService_Update_FullMethodName          = "/cores.ClassService/Update"
	ClassService_View_FullMethodName            = "/cores.ClassService/View"
	ClassService_Name_FullMethodName            = "/cores.ClassService/Name"
	ClassService_NameFull_FullMethodName        = "/cores.ClassService/NameFull"
	ClassService_Delete_FullMethodName          = "/cores.ClassService/Delete"
	ClassService_List_FullMethodName            = "/cores.ClassService/List"
	ClassService_Clone_FullMethodName           = "/cores.ClassService/Clone"
	ClassService_ViewWithDeleted_FullMethodName = "/cores.ClassService/ViewWithDeleted"
	ClassService_Pull_FullMethodName            = "/cores.ClassService/Pull"
	ClassService_Sync_FullMethodName            = "/cores.ClassService/Sync"
)

// ClassServiceClient is the client API for ClassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassServiceClient interface {
	Create(ctx context.Context, in *pb.Class, opts ...grpc.CallOption) (*pb.Class, error)
	Update(ctx context.Context, in *pb.Class, opts ...grpc.CallOption) (*pb.Class, error)
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Class, error)
	Name(ctx context.Context, in *ClassNameRequest, opts ...grpc.CallOption) (*pb.Class, error)
	NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Class, error)
	Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error)
	List(ctx context.Context, in *ClassListRequest, opts ...grpc.CallOption) (*ClassListResponse, error)
	Clone(ctx context.Context, in *ClassCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error)
	ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Class, error)
	Pull(ctx context.Context, in *ClassPullRequest, opts ...grpc.CallOption) (*ClassPullResponse, error)
	Sync(ctx context.Context, in *pb.Class, opts ...grpc.CallOption) (*pb.MyBool, error)
}

type classServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassServiceClient(cc grpc.ClientConnInterface) ClassServiceClient {
	return &classServiceClient{cc}
}

func (c *classServiceClient) Create(ctx context.Context, in *pb.Class, opts ...grpc.CallOption) (*pb.Class, error) {
	out := new(pb.Class)
	err := c.cc.Invoke(ctx, ClassService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Update(ctx context.Context, in *pb.Class, opts ...grpc.CallOption) (*pb.Class, error) {
	out := new(pb.Class)
	err := c.cc.Invoke(ctx, ClassService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Class, error) {
	out := new(pb.Class)
	err := c.cc.Invoke(ctx, ClassService_View_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Name(ctx context.Context, in *ClassNameRequest, opts ...grpc.CallOption) (*pb.Class, error) {
	out := new(pb.Class)
	err := c.cc.Invoke(ctx, ClassService_Name_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Class, error) {
	out := new(pb.Class)
	err := c.cc.Invoke(ctx, ClassService_NameFull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, ClassService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) List(ctx context.Context, in *ClassListRequest, opts ...grpc.CallOption) (*ClassListResponse, error) {
	out := new(ClassListResponse)
	err := c.cc.Invoke(ctx, ClassService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Clone(ctx context.Context, in *ClassCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, ClassService_Clone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Class, error) {
	out := new(pb.Class)
	err := c.cc.Invoke(ctx, ClassService_ViewWithDeleted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Pull(ctx context.Context, in *ClassPullRequest, opts ...grpc.CallOption) (*ClassPullResponse, error) {
	out := new(ClassPullResponse)
	err := c.cc.Invoke(ctx, ClassService_Pull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Sync(ctx context.Context, in *pb.Class, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, ClassService_Sync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassServiceServer is the server API for ClassService service.
// All implementations must embed UnimplementedClassServiceServer
// for forward compatibility
type ClassServiceServer interface {
	Create(context.Context, *pb.Class) (*pb.Class, error)
	Update(context.Context, *pb.Class) (*pb.Class, error)
	View(context.Context, *pb.Id) (*pb.Class, error)
	Name(context.Context, *ClassNameRequest) (*pb.Class, error)
	NameFull(context.Context, *pb.Name) (*pb.Class, error)
	Delete(context.Context, *pb.Id) (*pb.MyBool, error)
	List(context.Context, *ClassListRequest) (*ClassListResponse, error)
	Clone(context.Context, *ClassCloneRequest) (*pb.MyBool, error)
	ViewWithDeleted(context.Context, *pb.Id) (*pb.Class, error)
	Pull(context.Context, *ClassPullRequest) (*ClassPullResponse, error)
	Sync(context.Context, *pb.Class) (*pb.MyBool, error)
	mustEmbedUnimplementedClassServiceServer()
}

// UnimplementedClassServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClassServiceServer struct {
}

func (UnimplementedClassServiceServer) Create(context.Context, *pb.Class) (*pb.Class, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedClassServiceServer) Update(context.Context, *pb.Class) (*pb.Class, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedClassServiceServer) View(context.Context, *pb.Id) (*pb.Class, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedClassServiceServer) Name(context.Context, *ClassNameRequest) (*pb.Class, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedClassServiceServer) NameFull(context.Context, *pb.Name) (*pb.Class, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NameFull not implemented")
}
func (UnimplementedClassServiceServer) Delete(context.Context, *pb.Id) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedClassServiceServer) List(context.Context, *ClassListRequest) (*ClassListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedClassServiceServer) Clone(context.Context, *ClassCloneRequest) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedClassServiceServer) ViewWithDeleted(context.Context, *pb.Id) (*pb.Class, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewWithDeleted not implemented")
}
func (UnimplementedClassServiceServer) Pull(context.Context, *ClassPullRequest) (*ClassPullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedClassServiceServer) Sync(context.Context, *pb.Class) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedClassServiceServer) mustEmbedUnimplementedClassServiceServer() {}

// UnsafeClassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassServiceServer will
// result in compilation errors.
type UnsafeClassServiceServer interface {
	mustEmbedUnimplementedClassServiceServer()
}

func RegisterClassServiceServer(s grpc.ServiceRegistrar, srv ClassServiceServer) {
	s.RegisterService(&ClassService_ServiceDesc, srv)
}

func _ClassService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Class)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Create(ctx, req.(*pb.Class))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Class)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Update(ctx, req.(*pb.Class))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Name(ctx, req.(*ClassNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_NameFull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).NameFull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_NameFull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).NameFull(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Delete(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).List(ctx, req.(*ClassListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassCloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Clone(ctx, req.(*ClassCloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_ViewWithDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).ViewWithDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_ViewWithDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).ViewWithDeleted(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Pull(ctx, req.(*ClassPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Class)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Sync(ctx, req.(*pb.Class))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassService_ServiceDesc is the grpc.ServiceDesc for ClassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cores.ClassService",
	HandlerType: (*ClassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ClassService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ClassService_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _ClassService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _ClassService_Name_Handler,
		},
		{
			MethodName: "NameFull",
			Handler:    _ClassService_NameFull_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ClassService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ClassService_List_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _ClassService_Clone_Handler,
		},
		{
			MethodName: "ViewWithDeleted",
			Handler:    _ClassService_ViewWithDeleted_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _ClassService_Pull_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _ClassService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cores/class_service.proto",
}

const (
	AttrService_Create_FullMethodName              = "/cores.AttrService/Create"
	AttrService_Update_FullMethodName              = "/cores.AttrService/Update"
	AttrService_View_FullMethodName                = "/cores.AttrService/View"
	AttrService_Name_FullMethodName                = "/cores.AttrService/Name"
	AttrService_NameFull_FullMethodName            = "/cores.AttrService/NameFull"
	AttrService_Delete_FullMethodName              = "/cores.AttrService/Delete"
	AttrService_List_FullMethodName                = "/cores.AttrService/List"
	AttrService_Clone_FullMethodName               = "/cores.AttrService/Clone"
	AttrService_ViewWithDeleted_FullMethodName     = "/cores.AttrService/ViewWithDeleted"
	AttrService_Pull_FullMethodName                = "/cores.AttrService/Pull"
	AttrService_Sync_FullMethodName                = "/cores.AttrService/Sync"
	AttrService_GetValue_FullMethodName            = "/cores.AttrService/GetValue"
	AttrService_SetValue_FullMethodName            = "/cores.AttrService/SetValue"
	AttrService_SetValueForce_FullMethodName       = "/cores.AttrService/SetValueForce"
	AttrService_GetValueByName_FullMethodName      = "/cores.AttrService/GetValueByName"
	AttrService_SetValueByName_FullMethodName      = "/cores.AttrService/SetValueByName"
	AttrService_SetValueByNameForce_FullMethodName = "/cores.AttrService/SetValueByNameForce"
	AttrService_Upload_FullMethodName              = "/cores.AttrService/Upload"
)

// AttrServiceClient is the client API for AttrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttrServiceClient interface {
	Create(ctx context.Context, in *pb.Attr, opts ...grpc.CallOption) (*pb.Attr, error)
	Update(ctx context.Context, in *pb.Attr, opts ...grpc.CallOption) (*pb.Attr, error)
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Attr, error)
	Name(ctx context.Context, in *AttrNameRequest, opts ...grpc.CallOption) (*pb.Attr, error)
	NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Attr, error)
	Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error)
	List(ctx context.Context, in *AttrListRequest, opts ...grpc.CallOption) (*AttrListResponse, error)
	Clone(ctx context.Context, in *AttrCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error)
	ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Attr, error)
	Pull(ctx context.Context, in *AttrPullRequest, opts ...grpc.CallOption) (*AttrPullResponse, error)
	Sync(ctx context.Context, in *pb.Attr, opts ...grpc.CallOption) (*pb.MyBool, error)
	GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.AttrValue, error)
	SetValue(ctx context.Context, in *pb.AttrValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	SetValueForce(ctx context.Context, in *pb.AttrValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	GetValueByName(ctx context.Context, in *AttrGetValueByNameRequest, opts ...grpc.CallOption) (*AttrNameValue, error)
	SetValueByName(ctx context.Context, in *AttrNameValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	SetValueByNameForce(ctx context.Context, in *AttrNameValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	Upload(ctx context.Context, in *AttrValueUploadRequest, opts ...grpc.CallOption) (*AttrValueUploadResponse, error)
}

type attrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttrServiceClient(cc grpc.ClientConnInterface) AttrServiceClient {
	return &attrServiceClient{cc}
}

func (c *attrServiceClient) Create(ctx context.Context, in *pb.Attr, opts ...grpc.CallOption) (*pb.Attr, error) {
	out := new(pb.Attr)
	err := c.cc.Invoke(ctx, AttrService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) Update(ctx context.Context, in *pb.Attr, opts ...grpc.CallOption) (*pb.Attr, error) {
	out := new(pb.Attr)
	err := c.cc.Invoke(ctx, AttrService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Attr, error) {
	out := new(pb.Attr)
	err := c.cc.Invoke(ctx, AttrService_View_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) Name(ctx context.Context, in *AttrNameRequest, opts ...grpc.CallOption) (*pb.Attr, error) {
	out := new(pb.Attr)
	err := c.cc.Invoke(ctx, AttrService_Name_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Attr, error) {
	out := new(pb.Attr)
	err := c.cc.Invoke(ctx, AttrService_NameFull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, AttrService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) List(ctx context.Context, in *AttrListRequest, opts ...grpc.CallOption) (*AttrListResponse, error) {
	out := new(AttrListResponse)
	err := c.cc.Invoke(ctx, AttrService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) Clone(ctx context.Context, in *AttrCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, AttrService_Clone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Attr, error) {
	out := new(pb.Attr)
	err := c.cc.Invoke(ctx, AttrService_ViewWithDeleted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) Pull(ctx context.Context, in *AttrPullRequest, opts ...grpc.CallOption) (*AttrPullResponse, error) {
	out := new(AttrPullResponse)
	err := c.cc.Invoke(ctx, AttrService_Pull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) Sync(ctx context.Context, in *pb.Attr, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, AttrService_Sync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.AttrValue, error) {
	out := new(pb.AttrValue)
	err := c.cc.Invoke(ctx, AttrService_GetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) SetValue(ctx context.Context, in *pb.AttrValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, AttrService_SetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) SetValueForce(ctx context.Context, in *pb.AttrValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, AttrService_SetValueForce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) GetValueByName(ctx context.Context, in *AttrGetValueByNameRequest, opts ...grpc.CallOption) (*AttrNameValue, error) {
	out := new(AttrNameValue)
	err := c.cc.Invoke(ctx, AttrService_GetValueByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) SetValueByName(ctx context.Context, in *AttrNameValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, AttrService_SetValueByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) SetValueByNameForce(ctx context.Context, in *AttrNameValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, AttrService_SetValueByNameForce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attrServiceClient) Upload(ctx context.Context, in *AttrValueUploadRequest, opts ...grpc.CallOption) (*AttrValueUploadResponse, error) {
	out := new(AttrValueUploadResponse)
	err := c.cc.Invoke(ctx, AttrService_Upload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttrServiceServer is the server API for AttrService service.
// All implementations must embed UnimplementedAttrServiceServer
// for forward compatibility
type AttrServiceServer interface {
	Create(context.Context, *pb.Attr) (*pb.Attr, error)
	Update(context.Context, *pb.Attr) (*pb.Attr, error)
	View(context.Context, *pb.Id) (*pb.Attr, error)
	Name(context.Context, *AttrNameRequest) (*pb.Attr, error)
	NameFull(context.Context, *pb.Name) (*pb.Attr, error)
	Delete(context.Context, *pb.Id) (*pb.MyBool, error)
	List(context.Context, *AttrListRequest) (*AttrListResponse, error)
	Clone(context.Context, *AttrCloneRequest) (*pb.MyBool, error)
	ViewWithDeleted(context.Context, *pb.Id) (*pb.Attr, error)
	Pull(context.Context, *AttrPullRequest) (*AttrPullResponse, error)
	Sync(context.Context, *pb.Attr) (*pb.MyBool, error)
	GetValue(context.Context, *pb.Id) (*pb.AttrValue, error)
	SetValue(context.Context, *pb.AttrValue) (*pb.MyBool, error)
	SetValueForce(context.Context, *pb.AttrValue) (*pb.MyBool, error)
	GetValueByName(context.Context, *AttrGetValueByNameRequest) (*AttrNameValue, error)
	SetValueByName(context.Context, *AttrNameValue) (*pb.MyBool, error)
	SetValueByNameForce(context.Context, *AttrNameValue) (*pb.MyBool, error)
	Upload(context.Context, *AttrValueUploadRequest) (*AttrValueUploadResponse, error)
	mustEmbedUnimplementedAttrServiceServer()
}

// UnimplementedAttrServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAttrServiceServer struct {
}

func (UnimplementedAttrServiceServer) Create(context.Context, *pb.Attr) (*pb.Attr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAttrServiceServer) Update(context.Context, *pb.Attr) (*pb.Attr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAttrServiceServer) View(context.Context, *pb.Id) (*pb.Attr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedAttrServiceServer) Name(context.Context, *AttrNameRequest) (*pb.Attr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedAttrServiceServer) NameFull(context.Context, *pb.Name) (*pb.Attr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NameFull not implemented")
}
func (UnimplementedAttrServiceServer) Delete(context.Context, *pb.Id) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAttrServiceServer) List(context.Context, *AttrListRequest) (*AttrListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAttrServiceServer) Clone(context.Context, *AttrCloneRequest) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedAttrServiceServer) ViewWithDeleted(context.Context, *pb.Id) (*pb.Attr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewWithDeleted not implemented")
}
func (UnimplementedAttrServiceServer) Pull(context.Context, *AttrPullRequest) (*AttrPullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedAttrServiceServer) Sync(context.Context, *pb.Attr) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedAttrServiceServer) GetValue(context.Context, *pb.Id) (*pb.AttrValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedAttrServiceServer) SetValue(context.Context, *pb.AttrValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedAttrServiceServer) SetValueForce(context.Context, *pb.AttrValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValueForce not implemented")
}
func (UnimplementedAttrServiceServer) GetValueByName(context.Context, *AttrGetValueByNameRequest) (*AttrNameValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValueByName not implemented")
}
func (UnimplementedAttrServiceServer) SetValueByName(context.Context, *AttrNameValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValueByName not implemented")
}
func (UnimplementedAttrServiceServer) SetValueByNameForce(context.Context, *AttrNameValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValueByNameForce not implemented")
}
func (UnimplementedAttrServiceServer) Upload(context.Context, *AttrValueUploadRequest) (*AttrValueUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedAttrServiceServer) mustEmbedUnimplementedAttrServiceServer() {}

// UnsafeAttrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttrServiceServer will
// result in compilation errors.
type UnsafeAttrServiceServer interface {
	mustEmbedUnimplementedAttrServiceServer()
}

func RegisterAttrServiceServer(s grpc.ServiceRegistrar, srv AttrServiceServer) {
	s.RegisterService(&AttrService_ServiceDesc, srv)
}

func _AttrService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Attr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Create(ctx, req.(*pb.Attr))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Attr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Update(ctx, req.(*pb.Attr))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Name(ctx, req.(*AttrNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_NameFull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).NameFull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_NameFull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).NameFull(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Delete(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).List(ctx, req.(*AttrListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrCloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Clone(ctx, req.(*AttrCloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_ViewWithDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).ViewWithDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_ViewWithDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).ViewWithDeleted(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Pull(ctx, req.(*AttrPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Attr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Sync(ctx, req.(*pb.Attr))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).GetValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.AttrValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).SetValue(ctx, req.(*pb.AttrValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_SetValueForce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.AttrValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).SetValueForce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_SetValueForce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).SetValueForce(ctx, req.(*pb.AttrValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_GetValueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrGetValueByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).GetValueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_GetValueByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).GetValueByName(ctx, req.(*AttrGetValueByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_SetValueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrNameValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).SetValueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_SetValueByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).SetValueByName(ctx, req.(*AttrNameValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_SetValueByNameForce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrNameValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).SetValueByNameForce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_SetValueByNameForce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).SetValueByNameForce(ctx, req.(*AttrNameValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttrService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrValueUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttrServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttrService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttrServiceServer).Upload(ctx, req.(*AttrValueUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttrService_ServiceDesc is the grpc.ServiceDesc for AttrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cores.AttrService",
	HandlerType: (*AttrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AttrService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AttrService_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _AttrService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _AttrService_Name_Handler,
		},
		{
			MethodName: "NameFull",
			Handler:    _AttrService_NameFull_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AttrService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AttrService_List_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _AttrService_Clone_Handler,
		},
		{
			MethodName: "ViewWithDeleted",
			Handler:    _AttrService_ViewWithDeleted_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _AttrService_Pull_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _AttrService_Sync_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _AttrService_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _AttrService_SetValue_Handler,
		},
		{
			MethodName: "SetValueForce",
			Handler:    _AttrService_SetValueForce_Handler,
		},
		{
			MethodName: "GetValueByName",
			Handler:    _AttrService_GetValueByName_Handler,
		},
		{
			MethodName: "SetValueByName",
			Handler:    _AttrService_SetValueByName_Handler,
		},
		{
			MethodName: "SetValueByNameForce",
			Handler:    _AttrService_SetValueByNameForce_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _AttrService_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cores/class_service.proto",
}
